export const FETCH_ISSUES = "FETCH_ISSUES";
export const GET_PROJECT_ID = "GET_PROJECT_ID";
export const GET_SEARCH_KEYWORD = "GET_SEARCH_KEYWORD";
export const GET_SORT_FIELD = "GET_SORT_FIELD";
export const GET_SORT_DIRECTION = "GET_SORT_DIRECTION";
export const GET_FILTER_IS_CLOSED = "GET_FILTER_IS_CLOSED";
export const GET_FILTER_IS_TOP = "GET_FILTER_IS_TOP";
